name: Bump Version

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
      -
        name: Get gem version
        run: |
          echo RUBY_VERSION=$(curl -fsSL https://pages.github.com/versions.json | jq -r '."ruby"') | tee /dev/stderr >> $GITHUB_ENV
          echo GEM_VERSION=$(curl -fsSL https://pages.github.com/versions.json | jq -r '."github-pages"') | tee /dev/stderr >> $GITHUB_ENV
      -
        name: Get bundler version
        run: |
          echo BUNDLER_VERSION=$(curl -fsSL https://rubygems.org/api/v1/versions/bundler.json | jq -r ".[] | select(.ruby_version) | select(.ruby_version | ltrimstr(\">= \") | split(\".\") <= $(echo \"${RUBY_VERSION}\" | jq -c "split(\".\")")) | select(.number | test(\"^\\\\d+\\\\.\\\\d+\\\\.\\\\d+\$\")) | .number" | head -n1) | tee /dev/stderr >> $GITHUB_ENV
      -
        name: Bump
        run: |
          sed Dockerfile -i -e "s/\(FROM ruby\):.*/\1:${RUBY_VERSION}-slim/"
          sed Dockerfile -i -e "s/\(\"github-pages\",\) \"[0-9]\+\"/\1 \"${GEM_VERSION}\"/"
          sed Dockerfile -i -e "s/\(bundler -v\) [0-9.]\+/\1 ${BUNDLER_VERSION}/"
          if ! git diff --exit-code
          then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "Bump version to ${GEM_VERSION}"
            git tag ${GEM_VERSION}
            git push
            git push --tags
          fi
